SYNCQT.HEADER_FILES         = ../../include/QtXmlRPC/qtxmlrpc.h
SYNCQT.HEADER_CLASSES       = ../../include/QtXmlRPC/QtXmlRPC
SYNCQT.PRIVATE_HEADER_FILES =
SYNCQT.QPA_HEADER_FILES     =
SYNCQT.INJECTIONS           =
